# Generated by Django 6.0.2 on 2026-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPOINTMENTS', '0002_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('DENTISTRY', 'Dentistry'), ('CARDIOLOGIST', 'Cardiologist'), ('ORTHOPEDIC', 'Orthopedic')], max_length=100),
        ),
    ]
