# Generated by Django 6.0.2 on 2026-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPOINTMENTS', '0003_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('DENTISTRY', 'Dentistry'), ('CARDIOLOGIST', 'Cardiologist'), ('ORTHOPEDIST', 'Orthopedist')], max_length=100),
        ),
    ]
